version: v2beta1
name: ahoy

dependencies:
  shell:
    path: ./apps/shell

# Pipeline configuration for orchestrating all services
pipelines:
  dev:
    run: |
      run_dependencies --all

  prod:
    run: |
      # Build all services
      devspace build
      # Deploy to production environment
      devspace deploy --namespace production

  # Individual service pipelines
  shell-dev:
    run: |
      devspace build shell
      devspace deploy shell
      devspace dev shell
