version: v2beta1
name: ahoy

dependencies:
  shell:
    path: ./apps/shell
  auth:
    path: ./apps/auth
  user:
    path: ./apps/user

# Pipeline configuration for orchestrating all services
pipelines:
  dev:
    run: |
      # Build all services
      devspace build
      # Deploy to development environment
      devspace deploy
      # Start development mode for all services
      devspace dev

  prod:
    run: |
      # Build all services
      devspace build
      # Deploy to production environment
      devspace deploy --namespace production

  # Individual service pipelines
  shell-dev:
    run: |
      devspace build shell
      devspace deploy shell
      devspace dev shell

  auth-dev:
    run: |
      devspace build auth
      devspace deploy auth
      devspace dev auth

  user-dev:
    run: |
      devspace build user
      devspace deploy user
      devspace dev user

# Global hooks for shared functionality
hooks:
  - command: echo "Starting Ahoy Microservices Development Environment"
    events:
      - before:dev
  - command: echo "All services deployed successfully"
    events:
      - after:deploy
