{{- if .Values.shell.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-shell
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app: shell
spec:
  type: {{ .Values.shell.service.type }}
  ports:
    - port: {{ .Values.shell.service.port }}
      targetPort: {{ .Values.shell.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
    app: shell
{{- end }} 