version: v2beta1
name: user

# Service-specific variables
vars:
  SERVICE_NAME: "user"
  SERVICE_PORT: "3002"
  PROJECT_NAME: "ahoy-microservices"
  REGISTRY: "ghcr.io"
  IMAGE_TAG: "latest"

# Images configuration
images:
  user:
    dockerfile: ./Dockerfile
    context: .
    tags:
      - ${REGISTRY}/${PROJECT_NAME}/${SERVICE_NAME}:${IMAGE_TAG}

# Deployments configuration
deployments:
  user:
    helm:
      chart:
        name: ../../charts/microservices
      values:
        user:
          enabled: true
          image: ghcr.io/ahoy-microservices/user:latest
          port: ${SERVICE_PORT}
          replicas: 2
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi
          service:
            type: ClusterIP
            port: ${SERVICE_PORT}
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: database-url
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3001"

# Development configuration
dev:
  user:
    labelSelector:
      app: ${SERVICE_NAME}
    container: ${SERVICE_NAME}
    workingDir: /app
    sync:
      - path: ./
        excludePaths:
          - node_modules/
          - .git/
          - dist/
          - build/
    ports:
      - port: "${SERVICE_PORT}:${SERVICE_PORT}"
    terminal:
      command: npm run dev
    logs:
      enabled: true

# Service-specific pipelines
pipelines:
  dev:
    run: |
      # Build the user service
      devspace build user
      # Deploy to development environment
      devspace deploy user
      # Start development mode
      devspace dev user

  build:
    run: |
      # Build the user service
      devspace build user

  deploy:
    run: |
      # Deploy the user service
      devspace deploy user

  logs:
    run: |
      # View logs for the user service
      devspace logs user

  test:
    run: |
      # Run tests for the user service
      npm test

# Service-specific hooks
hooks:
  - command: echo "Building ${SERVICE_NAME} service..."
    events:
      - before:build
  - command: echo "${SERVICE_NAME} service built successfully"
    events:
      - after:build
  - command: echo "Deploying ${SERVICE_NAME} service..."
    events:
      - before:deploy
  - command: echo "${SERVICE_NAME} service deployed successfully"
    events:
      - after:deploy
