version: v2beta1
name: projects

dependencies:
  backend:
    path: ./backend
    pipeline: dev
  frontend:
    path: ./frontend
    pipeline: dev
  shell:
    path: ../shell
    pipeline: dev

# This is a list of `pipelines` that DevSpace can execute
pipelines:
  dev:
    run: |-
      run_dependencies backend frontend

  dev-with-shell:
    run: |-
      run_dependencies backend frontend shell

  build: run_dependencies --all --pipeline build

  # You can run this pipeline via `devspace deploy`
  deploy:
    run: |-
      run_dependencies --all --pipeline deploy

commands:
  with-shell: |-
    devspace dev --pipeline dev-with-shell
