version: v2beta1
name: projects

dependencies:
  projects-backend:
    path: ./backend
    pipeline: dev
  projects-frontend:
    path: ./frontend
    pipeline: dev

# This is a list of `pipelines` that DevSpace can execute
pipelines:
  dev:
    run: |-
      run_dependencies --all

  build: run_dependencies --all --pipeline build

  # You can run this pipeline via `devspace deploy`
  deploy:
    run: |-
      run_dependencies --all --pipeline deploy
