version: v2beta1
name: widget

# Service-specific variables
vars:
  IMAGE_TAG: "latest"
  WIDGET_PORT: "3003"

# This is a list of `pipelines` that DevSpace can execute
pipelines:
  dev:
    run: |-
      run_dependencies --all       
      ensure_pull_secrets --all 
      create_deployments --all 
      start_dev widget

  build:
    run: |
      build_images --all -t $(git describe --always)

  # You can run this pipeline via `devspace deploy`
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag and push all images
      create_deployments --all

# Images configuration
images:
  widget:
    image: ghcr.io/ahoy/widget:${IMAGE_TAG}
    dockerfile: ./Dockerfile
    buildArgs:
      NODE_ENV: development

# Deployments configuration
deployments:
  widget:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: image(widget)
        service:
          ports:
            - port: ${WIDGET_PORT}
        env:
          - name: NODE_ENV
            value: development
          - name: PORT
            value: ${WIDGET_PORT}

# Development configuration
dev:
  widget:
    imageSelector: image(widget)
    devImage: node:22-alpine
    workingDir: /app
    sync:
      - path: ./
        excludePaths:
          - node_modules/
          - .git/
          - dist/
          - build/
          - .angular/
        startContainer: true
        onUpload:
          exec:
            - command: |-
                echo "Installing dependencies..."
                npm install
    command: ["npm", "run", "dev"]
    logs:
      enabled: true
    ssh:
      enabled: true
    ports:
      - port: ${WIDGET_PORT}
    env:
      - name: NODE_ENV
        value: development
      - name: PORT
        value: ${WIDGET_PORT}
    open:
      - url: http://localhost:${WIDGET_PORT}
