replicaCount: 1

image:
  repository: ahoy-projects-backend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3002

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: NODE_ENV
    value: "development"
  - name: PORT
    value: "3002"
  - name: DB_HOST
    value: "postgres-primary"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "ahoy_projects"
  - name: DB_USER
    value: "postgres"
  - name: DB_PASSWORD
    value: "ahoy123"
