apiVersion: v2
name: microservices
description: A Helm chart for Ahoy Microservices Architecture
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - kubernetes
  - devspace
home: https://github.com/your-org/ahoy-microservices
sources:
  - https://github.com/your-org/ahoy-microservices
maintainers:
  - name: Your Name
    email: your.email@example.com
